# Python program to predict Stock Price using ML Algorithm

In [25]:
# Import Libraries
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

### Data Preparation

In [28]:
def prepare_data(df,forecast_col,forecast_out,test_size):
    

    
    
    response = [X_train,X_test , Y_train, Y_test , X_lately]
    return response

### Import Dataset

In [29]:
df= pd.read_csv("C:\\Users\\shrey\\Downloads\\Stock_Prices.csv")
df

ticker   open  close  adj_close    low   high   volume        date
0           AHH  11.50  11.58   8.493155  11.25  11.68  4633900  2013-05-08
1           AHH  11.66  11.55   8.471151  11.50  11.66   275800  2013-05-09
2           AHH  11.55  11.60   8.507822  11.50  11.60   277100  2013-05-10
3           AHH  11.63  11.65   8.544494  11.55  11.65   147400  2013-05-13
4           AHH  11.60  11.53   8.456484  11.50  11.60   184100  2013-05-14
...         ...    ...    ...        ...    ...    ...      ...         ...
20973884    NZF  14.60  14.59  14.590000  14.58  14.62   137500  2018-08-20
20973885    NZF  14.60  14.58  14.580000  14.57  14.61   151200  2018-08-21
20973886    NZF  14.58  14.59  14.590000  14.57  14.63   185400  2018-08-22
20973887    NZF  14.60  14.57  14.570000  14.57  14.64   135600  2018-08-23
20973888    NZF  14.60  14.69  14.690000  14.59  14.69   180900  2018-08-24

[20973889 rows x 8 columns]

### Perform necessary operations

In [30]:
label = df[forecast_col].shift(-forecast_out)
label

0           11.73
1           11.83
2           11.75
3           11.61
4           11.70
            ...  
20973884      NaN
20973885      NaN
20973886      NaN
20973887      NaN
20973888      NaN
Name: close, Length: 20973889, dtype: float64

In [31]:
X = np.array(df[[forecast_col]]) 
X = preprocessing.scale(X)
X

array([[-0.02248448],
       [-0.02249493],
       [-0.02247751],
       ...,
       [-0.02143575],
       [-0.02144272],
       [-0.02140091]])

In [32]:
X_lately = X[-forecast_out:]
X_lately

array([[-0.02142182],
       [-0.02144621],
       [-0.02143575],
       [-0.02143575],
       [-0.02143924],
       [-0.02143575],
       [-0.02144272],
       [-0.02140091]])

In [33]:
X = X[:-forecast_out]
X

array([[-0.02248448],
       [-0.02249493],
       [-0.02247751],
       ...,
       [-0.02142879],
       [-0.02142879],
       [-0.02143575]])

In [34]:
label.dropna(inplace=True)
y = np.array(label) 
y

array([11.72999954, 11.82999992, 11.75      , ..., 14.59000015,
       14.56999969, 14.68999958])

In [35]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=test_size, random_state=0)


In [36]:
forecast_col = 'close'  # Column on which we have to perform forecasting
forecast_out = 8 # How many Forecast values you want...?
test_size = 0.2 # How far we wanna test

### Applyting Machine Learning Algorithm -: Linear Regression

In [37]:
(X_train, X_test, Y_train, Y_test , X_lately) =prepare_data(df,forecast_col,forecast_out,test_size); #calling the method were the cross validation and data preperation is in
learner = LinearRegression() #initializing linear regression model

learner.fit(X_train,Y_train) #training the linear regression model

LinearRegression()

In [38]:
score=learner.score(X_test,Y_test)#testing the linear regression model
forecast= learner.predict(X_lately) #set that will contain the forecasted data
response={}#creting json object
response['test_score']=score
response['forecast_set']=forecast

print(response)

{'test_score': 0.04000606166798526, 'forecast_set': array([63.55343092, 63.53929716, 63.54535446, 63.54535446, 63.5433353 ,
       63.54535446, 63.54131614, 63.56554552])}
